//go:build windows
// +build windows

package mgl

import (
	"github.com/go-gl/gl/v4.4-core/gl"
)

// GetFrameBufferStatusString はフレームバッファステータスコードを文字列に変換
func GetFrameBufferStatusString(status uint32) string {
	switch status {
	case gl.FRAMEBUFFER_COMPLETE:
		return "FRAMEBUFFER_COMPLETE"
	case gl.FRAMEBUFFER_INCOMPLETE_ATTACHMENT:
		return "FRAMEBUFFER_INCOMPLETE_ATTACHMENT"
	case gl.FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT:
		return "FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT"
	case gl.FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER:
		return "FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER"
	case gl.FRAMEBUFFER_INCOMPLETE_READ_BUFFER:
		return "FRAMEBUFFER_INCOMPLETE_READ_BUFFER"
	case gl.FRAMEBUFFER_UNSUPPORTED:
		return "FRAMEBUFFER_UNSUPPORTED"
	case gl.FRAMEBUFFER_INCOMPLETE_MULTISAMPLE:
		return "FRAMEBUFFER_INCOMPLETE_MULTISAMPLE"
	case gl.FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS:
		return "FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS"
	default:
		return "UNKNOWN_ERROR"
	}
}
