/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: bullet.i

package mbt

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stddef.h>
#include <stdint.h>


typedef ptrdiff_t intgo;
typedef size_t uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


extern void _wrap_Swig_free_mbt_e2760843bed3e3b0(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_mbt_e2760843bed3e3b0(swig_intgo arg1);
extern uintptr_t _wrap_NewBtDefaultCollisionConfiguration_mbt_e2760843bed3e3b0(void);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


func getSwigcptr(v interface { Swigcptr() uintptr }) uintptr {
	if v == nil {
		return 0
	}
	return v.Swigcptr()
}


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_mbt_e2760843bed3e3b0(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_mbt_e2760843bed3e3b0(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func NewBtDefaultCollisionConfiguration() (_swig_ret BtDefaultCollisionConfiguration) {
	var swig_r BtDefaultCollisionConfiguration
	swig_r = (BtDefaultCollisionConfiguration)(SwigcptrBtDefaultCollisionConfiguration(C._wrap_NewBtDefaultCollisionConfiguration_mbt_e2760843bed3e3b0()))
	return swig_r
}


type SwigcptrBtDefaultCollisionConfiguration uintptr
type BtDefaultCollisionConfiguration interface {
	Swigcptr() uintptr;
}
func (p SwigcptrBtDefaultCollisionConfiguration) Swigcptr() uintptr {
	return uintptr(p)
}

