/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: C:\MMD\mlib_go\pkg\infra\bt\bullet.i

#ifndef SWIG_bt_WRAP_H_
#define SWIG_bt_WRAP_H_

class Swig_memory;

class SwigDirector_btMDebugDrawLiner : public btMDebugDrawLiner
{
 public:
  SwigDirector_btMDebugDrawLiner(int swig_p);
  virtual ~SwigDirector_btMDebugDrawLiner();
  virtual void drawLine(btVector3 const &from,btVector3 const &to,btVector3 const &color);
 private:
  intgo go_val;
  Swig_memory *swig_mem;
};

#endif
