package window

type IAppState interface {
	Frame() float64
	SetFrame(frame float64)
	ChangeFrame(frame float64)
	AddFrame(v float64)
	MaxFrame() int
	SetMaxFrame(maxFrame int)
	PrevFrame() int
	SetPrevFrame(prevFrame int)
	IsEnabledFrameDrop() bool
	SetEnabledFrameDrop(enabled bool)
	IsEnabledPhysics() bool
	SetEnabledPhysics(enabled bool)
	IsPhysicsReset() bool
	SetPhysicsReset(reset bool)
	IsShowNormal() bool
	SetShowNormal(show bool)
	IsShowWire() bool
	SetShowWire(show bool)
	IsShowSelectedVertex() bool
	SetShowSelectedVertex(show bool)
	IsShowBoneAll() bool
	SetShowBoneAll(show bool)
	IsShowBoneIk() bool
	SetShowBoneIk(show bool)
	IsShowBoneEffector() bool
	SetShowBoneEffector(show bool)
	IsShowBoneFixed() bool
	SetShowBoneFixed(show bool)
	IsShowBoneRotate() bool
	SetShowBoneRotate(show bool)
	IsShowBoneTranslate() bool
	SetShowBoneTranslate(show bool)
	IsShowBoneVisible() bool
	SetShowBoneVisible(show bool)
	IsShowRigidBodyFront() bool
	SetShowRigidBodyFront(show bool)
	IsShowRigidBodyBack() bool
	SetShowRigidBodyBack(show bool)
	IsShowJoint() bool
	SetShowJoint(show bool)
	IsShowInfo() bool
	SetShowInfo(show bool)
	IsLimitFps30() bool
	SetLimitFps30(limit bool)
	IsLimitFps60() bool
	SetLimitFps60(limit bool)
	IsUnLimitFps() bool
	SetUnLimitFps(limit bool)
	IsUnLimitFpsDeform() bool
	SetUnLimitFpsDeform(limit bool)
	IsLogLevelDebug() bool
	SetLogLevelDebug(log bool)
	IsLogLevelVerbose() bool
	SetLogLevelVerbose(log bool)
	IsLogLevelIkVerbose() bool
	SetLogLevelIkVerbose(log bool)
	IsClosed() bool
	SetClosed(closed bool)
	Playing() bool
	TriggerPlay(p bool)
	SpfLimit() float64
	SetSpfLimit(spf float64)
}
